### ISSUE TITLE
Run utPLSQL test greyed out in Schema Browser (other schema and own schema)

### ISSUE THREAD

**Issue by mhoys** [utPLSQL/utPLSQL-SQLDeveloper#111]
Hi,
I'm using the utPLSQL extension version 1.2.0 with SQL Developer 19.4.
I can right-click in the connections window and run utPLSQL tests on packages in my own schema, but I cannot do this on packages in another schema - the utPLSQL options are greyed out. Any idea what could be causing this? If I run them like this from my own schema, it works fine:

set serveroutput on
begin
  ut.run('other_schema.ut_package');
end;

PS: I have enough rights to create and execute objects in the other schema.

Thanks
Matthias

**Comment by mhoys** [comment]
Hi Philipp,

We are using utPLSQL version v3.1.9.3270.

I executed your piece of PL/SQL code and it returned 1 in my case, so this looks ok.

However, I have found something else based on your feedback.
I normally browse to the objects of other users by right-clicking in my schema name in the connections window, then choose "Schema Browser" and select the required schema. The utPLSQL options are greyed out there! However, when I try it your way and open the other schema from the "Other Users" folder in my schema, it works fine and the utPLSQL context menu is correctly enabled! Can you reproduce this behaviour? Let me know if you need more information.

Thanks,
Matthias

**Comment by PhilippSalvisberg** [comment]
Yes, I can reproduce it.

![image](https://user-images.githubusercontent.com/3883171/90987233-a8977580-e589-11ea-8ffd-83a8b0c8207e.png)

It looks like it's not possible to select test packages in the Schema Browser. It does not matter which schema is selected. Does not work with the own schema schema. I consider this a bug. Thank you for reporting it.

**Comment by mhoys** [comment]
Thanks, good to know it's a bug and not something related to my configuration ;-)

**Comment by mhoys** [comment]
(oops maybe I should better not close this one)

**Comment by mhoys** [comment]
Thanks, I can confirm it's working fine now (I tried v1.2.1 with SQL Developer 20.2.
