### ISSUE TITLE
special characters in connection name

### ISSUE THREAD

**Issue by wolframhaussig** [utPLSQL/utPLSQL-SQLDeveloper#118]
It is just a minor beauty bug, but it would still be nice to see this fixed:
We have connections in the SQL-Developer named username@database, e.g. sys@local. When I use the button "run utplsql test" in sqldeveloper the utplsql shows the name wrongly in the history list:
![image](https://user-images.githubusercontent.com/13997737/101160915-185cd800-3630-11eb-99a7-3a2b5437df61.png)
Instead of SQL_TOOLS@lokal the UI shows SQL_TOOLS%40lokal

**Comment by PhilippSalvisberg** [comment]
Yes, I consider this a bug. Thanks for reporting.

**Comment by wolframhaussig** [comment]
@PhilippSalvisberg I have just tested your fix and it works: instead of %40 the @ sign will be displayed correctly. But I have found that the space character is displayed as a + sign (sorry for not finding that earlier)

**Comment by PhilippSalvisberg** [comment]
Thanks @wolframhaussig for checking. I wonder since when spaces are allowed in the connection name.

![image](https://user-images.githubusercontent.com/3883171/103511951-3a808a80-4e68-11eb-8b08-e4a538423928.png)

But I see that it works. Looks like they are treated in a special way. I'll fix that.

**Comment by wolframhaussig** [comment]
I am using version 20.2.0.175(Build 175.1842) but it worked before. I think it worked in version 18.x already but I am not sure when it started exactly.
