### ISSUE TITLE
Suitepath text overlays header

### ISSUE THREAD

**Issue by simasch** [utPLSQL/utPLSQL-SQLDeveloper#128]
As you can see in the attached screenshot the text of the test overlays the header during running the tests and scrolling in the table:

![image](https://user-images.githubusercontent.com/593352/103545731-4426e400-4ea2-11eb-83be-a48b74f9b7d7.png)

SQL/Developer version 19.2.1.247
utPLSQL for SQL Developer 1.3.0.20210103.170722 
Java(TM) Platform | 1.8.0_212
Windows 10

**Comment by PhilippSalvisberg** [comment]
Yes this is a know issue. Double buffering is already enabled. I currently do not see a way to fix this repainting issue during the run. At the end it should be ok. Right?

**Comment by simasch** [comment]
If the test run is finished and I scroll in the grid the UI is updated correctly, yes.

**Comment by PhilippSalvisberg** [comment]
Thanks for the feedback. That's what I experience. AFAIK there is nothing I can do about it (using existing Swing components of course). If you have an idea, then please let me know.

**Comment by simasch** [comment]
Ok Thanks for the information. I'll close the issue.
