### ISSUE TITLE
Change default value of "Show description (if present)" preference

### ISSUE THREAD

**Issue by mathewbutler** [utPLSQL/utPLSQL-SQLDeveloper#134]
(thanks again for the time and effort put into this extension - it's a real productivity improvement for database testing using Oracle SQL Developer)

Following on from [this discussion](https://utplsql.slack.com/archives/C0PK55Z08/p1609893840063200?thread_ts=1609850017.057200&cid=C0PK55Z08) in the utPLSQL slack channel;

The 1.3.1 release makes the tree-table view of tests the default (the use of this view being controlled via the “Show suites (hierarchical view of tests)" preference). In the tree table view, an improvement would be to see the descriptions associated with tests and context's if these are present. This can be controlled by the preference "Show description (if present)", but the default of this preference is "disabled".

This enhancement request, is to change the default value of the preference "Show description (if present)" to be "enabled".

Also, in the context of the introduction of the tree-table view, it's worth considering whether the other preference defaults are still sensible - though these aren't the subject of this enhancement request.

**Comment by PhilippSalvisberg** [comment]
Thanks Mathew. 

Maybe all of the Realtime Reporter options in the preferences should be enabled like this:

![image](https://user-images.githubusercontent.com/3883171/103933189-421f8800-5123-11eb-9c72-07b5c57ce7f4.png)

Impact for initial installations:

- The three counters (disabled, warning, info) will probably add just an additional line.
- Indicators (warning info) will leave less space for description.

Disabling information is probably more intuitive than enabling information.

**Comment by mathewbutler** [comment]
On the basis (based on slack discussion) that the state of any configured options changed by the user in a previous install are carried forward, then I think these defaults you have listed make sense.
