### ISSUE TITLE
Can't find libraries

### ISSUE THREAD

**Issue by tmrozek** [utPLSQL/utPLSQL-SQLDeveloper#136]
Hello, I'm trying to compile your sources and I've found it difficult so far. Could you please tell me where to find libraries such as oracle.javatools.data? I can't find it anywhere in the sqldeveloper zip file. 

Second thing - I suppose that in org.oddgen path to specific (17.*) sqldeveloper instalation is hardcoded.

**Comment by PhilippSalvisberg** [comment]
Thank you @tmrozek for reporting this bug. 

I could reproduce the problem in a different environment.

As a workaround you can add the following dependencies to the `pom.xml` of this project:

```xml
		<dependency>
			<!-- overriding oddgen dependency -->
			<groupId>oracle</groupId>
			<artifactId>javatools-nodeps</artifactId>
			<version>13.0.0</version>
			<scope>system</scope>
			<systemPath>${sqldev.basedir}/modules/oracle.javatools/javatools-nodeps.jar</systemPath>
		</dependency>
		<dependency>
			<!-- missing dependency for javax.annotation.Nullable -->
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
			<version>3.0.2</version>
			<scope>provided</scope>
		</dependency>
```

Then you should be able to build the project as described [here](https://github.com/utPLSQL/utPLSQL-SQLDeveloper#how-to-build).
