### ISSUE TITLE
Empty utPLSQL windows when `Show suites (hierarchical view of tests)?` is unchecked

### ISSUE THREAD

**Issue by eriktrip** [utPLSQL/utPLSQL-SQLDeveloper#138]
Hello
I installed the plug in in sql developer 20.4. The plugin worked fine, I tweaked some preferences and now I do not get any results anymore. Running ut.run works fine.
![image](https://user-images.githubusercontent.com/64896707/125259246-6c831580-e2ff-11eb-8634-869e8da40658.png)

Any help is appreciated
Regard Erik

**Comment by eriktrip** [comment]
I tried on another device with sql developer 19.4 and there are no problems there

**Comment by eriktrip** [comment]
I reinstalled utplsql and the proble has gone....

**Comment by eriktrip** [comment]
The problem is back, on both devices.
Any help would be appreciated

**Comment by PhilippSalvisberg** [comment]
Can you try "Reset Windows to Factory Settings"?

![image](https://user-images.githubusercontent.com/3883171/125273914-b5da6180-e30d-11eb-9469-2670af2c4a27.png)

In case the problem occurs again. Could you please provide a step-by-step description to reproduce the problem? Thanks!

**Comment by eriktrip** [comment]
Reset to factory settings does not solve the problem.
I installed utplsql, played around with test_between_str, installed the plugin, generate a test package based on an existing package. Run utPLSQL test. That worked, after that I implemented some procedures and played with annotations like %disabled and %context. At some time I got this problem.


Regards Erik
![image](https://user-images.githubusercontent.com/64896707/125277099-4d8d7f00-e311-11eb-9925-739813e423b6.png)

**Comment by PhilippSalvisberg** [comment]
Ok, the utPLSQL tab looks strange. I have currently no idea how to reproduce this.

Could you please run the following in a SQL worksheet and provide the output?

```sql
set serveroutput on
-- version information
declare
  l_version varchar2(255);
  l_compatibility varchar2(255);
begin
  dbms_utility.db_version( l_version, l_compatibility );
  dbms_output.put_line( l_version );
  dbms_output.put_line( l_compatibility );
end;
/
select substr(ut.version(),1,60) as ut_version from dual;
select * from v$version;
select * from nls_session_parameters;
select substr(dbms_utility.port_string,1,60) as port_string from dual;
-- test run
execute ut.run;
```

Furthermore, what happens when you close the utPLSQL window and run a test either from the editor or the Connections Window? Does it work? If yes, what are the excact steps to do to create such an empty utPLSQL window?

**Comment by eriktrip** [comment]
Thx!, that did the trick. I played around with those options. 
Regards Erik

**Comment by PhilippSalvisberg** [comment]
Keep issue open until the bug is fixed in the main branch.
