### ISSUE TITLE
Add support for disabled reason with utPLSQL v3.1.12

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#143]
With utPSLQL v3.1.12 we will allow users to provide reason when test is disabled.
See [PR 1183](https://github.com/utPLSQL/utPLSQL/pull/1183)
The disabled reason should be consumed by IDE and shown in test results window of utPLSQL.

**Comment by jgebal** [comment]
There is an issue open in PLSQLDeveloper plugin to address the same.
utPLSQL/utPLSQL-PLSQL-Developer#25

@simasch @PhilippSalvisberg @lwasylow 
Let's discuss the details of implementation there.

**Comment by PhilippSalvisberg** [comment]
The ut_realtime_reporter in utPLSQL v3.12 does not include the disabled reason. Hence it is currently not possible to show that in the UI. Maybe with v3.13.
