### ISSUE TITLE
plans to update to more recent SQL Developer version?

### ISSUE THREAD

**Issue by chris-seals** [utPLSQL/utPLSQL-SQLDeveloper#144]
Are there any plans to update the plug-in to work with SQL Developer 21+? I've been experiencing a number of perfomance issues (non-utplsql related) in my 20.2 SQL Developer, updated, but was sad to see I could no longer use your plugin.

**Comment by PhilippSalvisberg** [comment]
Actually the extension works with SQLDev 21.4.2. What are exactly your problems? Which version are you using what OS?

**Comment by chris-seals** [comment]
I've tried both the zip method and the update center method, it acts like it installs, but after it does the mandatory restart of SQL Developer, the plugin is not present whatsoever. I'm using SQL Dev 21.4.2.018.

**Comment by PhilippSalvisberg** [comment]
Can you show me the screenshot of the about dialog. There should be listed if the extension is installed.

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/3883171/154503743-d866d466-909e-4a6c-b3d1-f8e27947ceb0.png">

Another option to check the installation is the features Window (under Tools -> Features):

<img width="783" alt="image" src="https://user-images.githubusercontent.com/3883171/154504909-bb4dd06f-0655-4c2e-807e-4f4ee342cd64.png">

When it is installed. And the utPLSQL window does not show up then I suggest to call "Reset Windows To Factory Settings".

<img width="300" alt="image" src="https://user-images.githubusercontent.com/3883171/154504187-93b3cfef-9153-49d2-8c9b-13a70cf09e40.png">

To be clear, the utPLSQL extension is compatible with the most current SQLDev version. If it is not working in your environment then there is an issue with the setup.

**Comment by chris-seals** [comment]
I tried a third time to document each step, and had success... thank you for the clarification sir! My features were completely empty before I retried, so I think there were bigger issues at play. Thanks again.

**Comment by PhilippSalvisberg** [comment]
Does it work now?

**Comment by chris-seals** [comment]
Yes, all is well and it is showing up as present/behaving as I would expect.

**Comment by PhilippSalvisberg** [comment]
Happy to hear. Closing the issue.
