### ISSUE TITLE
Opportunities for silent rolllout with an SCCM like ACMP ?

### ISSUE THREAD

**Issue by STRG-ALT-DEFEAT** [utPLSQL/utPLSQL-SQLDeveloper#162]
Hello :) 

Is there a possibility to install the extension with a script?

I would like  to create a SCCM package.

Thank you for your help :)

**Comment by PhilippSalvisberg** [comment]
The extension is technically a JDeveloper extension. 

I found the following blog post regarding silent installation of a JDeveloper extension: 

https://blindauer.net/dotclear/post/2016/03/23/Oracle-Jdeveloper%3A-silent-install-of-extensions . 

The mentioned `ojwebupdate` tool exists in `sqldeveloper/jdev/bin`. However, I'm not sure if there is everything available in a SQL Developer installation.

Maybe you find out how it works. Good luck.

**Comment by PhilippSalvisberg** [comment]
I am closing the ticket due to inactivity. IMO the question has been answered.
