### ISSUE TITLE
Instructions for generating coverage report without access to public internet

### ISSUE THREAD

**Issue by mathewbutler** [utPLSQL/utPLSQL-SQLDeveloper#163]
- SQL Developer V20.4.1.407 (Build 407.006)
- utPLSQL SQL Developer Plugin V1.3.1.20210104.21005

Trying out the code coverage feature of the utPLSQL SQL Developer plugin and this not producing any output. I suspect a restriction since this is running in an environment with no public internet access.

- Right click on test package in SQL Developer
- Click on the [Code coverage...] option
- Nothing happens

The issues below suggest that the assets for offline usage may be required for this to work

- #110
- #120

Questions:

- Are the assets referred to in #110 now included in [V1.4.1](https://github.com/utPLSQL/utPLSQL-SQLDeveloper/releases/tag/v1.4.1) ?
- If not, I can import these to my environment and follow the instructions in #110 "assets can be copied into the same temporary directory as the HTML file.". Can you please advise of the location of this temporary directory?
- Is there anything else needed for the report to function offline other than the above?

Thanks in advance - and also thank you for producing this plug-in. The team I work on find this incredible useful.

**Comment by mathewbutler** [comment]
Revisiting the virtual desktop where I ran these coverage reports - these have been successfully generated. I can only assume they took a long time to be produced. 

I’m closing this.

**Comment by PhilippSalvisberg** [comment]
@mathewbutler Thanks for checking again. Sometimes it really is the case that problems are solved automatically if you just wait long enough. ;-)

ASFAIK @jgebal is looking for ways to reduce the overhead of large code coverage reports in the core framework. In the meantime it is a good idea to reduce to run just parts of large suites with code coverage. I know it's not always feasible, but I cannot to more at the moment.

**Comment by mathewbutler** [comment]
Appreciate the follow up, and the additional suggestions, and happy with your response. I genuinely thought I was seeing a different issue - thanks again.
