### ISSUE TITLE
Enable one unit test in a bunch of Unit Tests

### ISSUE THREAD

**Issue by doricardo** [utPLSQL/utPLSQL-SQLDeveloper#164]
We have a package that has 15 unit tests, Is there any possibility to run only one of them instead of mentioning `--%disabled `on the others 14 tests?

**Comment by jgebal** [comment]
ut.run('schema.package.procedure'); 

That sould do the trick.

**Comment by jgebal** [comment]
You can run individual test procedure from UI too.

**Comment by doricardo** [comment]
> ut.run('schema.package.procedure');
> 
> That sould do the trick.

Much appreciate mate

**Comment by jgebal** [comment]
You may also have a look into [utPLSQL documentation](https://www.utplsql.org/utPLSQL/latest/) for more details or look in the [resouces page](https://www.utplsql.org/resources.html#utplsql-sqldeveloper-extension) for some good blogs/videos.
