### ISSUE TITLE
Pressing Create code templates does nothing

### ISSUE THREAD

**Issue by largomike1** [utPLSQL/utPLSQL-SQLDeveloper#166]
Thanks for working on this project.  So far everything is working fine except I have no code templates.  I clicked the button Create code templates, but nothing happens.  I go back to code templates in preferences and there are no new templates. I am using version 21.4.3.063 Build 063.0100 of Oracle Sql Developer.  Any assistance is appreciated.

**Comment by PhilippSalvisberg** [comment]
Please try the following

1. Open Preferences and type `template` in the search bar and click on `Code Templates`. You should see a screen similar to this one:

![image](https://user-images.githubusercontent.com/3883171/233557161-acc89472-2012-4a0a-8e69-60615eb409f1.png)

2. Type `utplsql` in the search bar and click on `utPLSQL` and then on the `Generate utPLSQL test` tab. You should see a screen similar to this:

![image](https://user-images.githubusercontent.com/3883171/233557957-4b29861d-02a1-458e-a281-08b98203503a.png)

3. Amend the preferences, if necessary and then press on the button `Create code templates` and afterwards on the `OK` button as highlighted in the screenshot above.

4. Reopen preferences and type `template` in the search bar and click on `Code Templates`. You should see a screen similar to this one, highlighting the generated templates:

![image](https://user-images.githubusercontent.com/3883171/233558766-a6f00c25-291f-4a8c-b184-369c6664b2ae.png)

You can change the templates on this screen. However, they will be overwritten on regeneration. So maybe it's better to rename the templates.

To use the templates, you type the name of the template in a worksheet editor and press Ctrl-Space.

![image](https://user-images.githubusercontent.com/3883171/233559848-c2b13f98-7a43-44ec-a562-e7d6e7ac5ea6.png)

You can then select the template via the cursor keys and the Return key. The next screenshot shows the result for the second entry:

![image](https://user-images.githubusercontent.com/3883171/233560349-7bb0e21d-d46c-4d6c-8ce9-b977d1838400.png)

Now you can navigate with the tab keys and change the highlighted `package_name`.

Does this help? If not could you please describe at which step you experience a different result? Thank you.

**Comment by largomike1** [comment]
Thanks - that worked for me!
