### ISSUE TITLE
Cannot run tests with missing schema when editing a package

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#22]
When I open a unit test package that belongs to different user in package editor, SQLDeveloper is aware of the package owner (and is compiling the package into the owners schema).
The plugin however fails to extract the owner information and so:
- when trying to run tests from package editor with availability check enabled, the run option is not available
- when trying to run tests from package editor with availability check disabled, the `ut.run` is invoked for package without owner and so it fails when trying to find unit tests.

**Comment by PhilippSalvisberg** [comment]
Looks like a bug. Thanks for reporting.
