### ISSUE TITLE
Menu option "Run utPLSQL test" always disabled in Connections navigator tree (at sign)

### ISSUE THREAD

**Issue by teotiger** [utPLSQL/utPLSQL-SQLDeveloper#23]
When then connection name contains at sign ("@"), the "Run utPLSQL test" menu option is always disabled.

The associated connection node is not found and therefore no enable checks occur and the node stays disabled.

As a workaround do not use the at sign ("@") in the connection name.

**Comment by PhilippSalvisberg** [comment]
I can reproduce the issue. This is a bug. Thanks for reporting.

**Comment by PhilippSalvisberg** [comment]
this is a similar bug like in #16. Needs generic solution for "special" characters.
