### ISSUE TITLE
Can we have navigator shortcut to run tests on selected item?

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#4]
In editor, we can use `Alt+Shift+T` to run the tests.
Is it possible to have the same shortcut for navigator action?

**Comment by PhilippSalvisberg** [comment]
I'll have to check. For sure it is different than the accelerators configuration for commands/actions defined in the extension.xml (used in the PL/SQL editor context menu).

**Comment by PhilippSalvisberg** [comment]
According to @krisrice it is not possible to a assign an accelerator in this case. It's a limitation of the XML based extension.
