### ISSUE TITLE
utPLSQL suitepath is case-insensitive

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#44]
in Oddgen (Run test) window, suite paths are shown as duplicated if they are typed with upper/lower case in unit test package spec.

So from those two suitepaths:
```
--%suitepath(org.utplsql.core)
...
--%SUITEPATH(ORG.UTPLSQL.CORE)
```

We get separate trees/branches in navigator. 

Those should be converted into common (lower) case and displayed as one tree.

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting. I will fix it a.s.a.p.
