### ISSUE TITLE
Get listed on official SQLDeveloper extensions page

### ISSUE THREAD

**Issue by Shoelace** [utPLSQL/utPLSQL-SQLDeveloper#58]
should get this extension listed on the "official" list

see 
https://www.oracle.com/technetwork/developer-tools/sql-developer/extensions-083825.html#available

the text at the bottom of teh page says 

> Please contact jeff.d.smith@oracle.com, if you'd like to upload your extension on this page.

**Comment by PhilippSalvisberg** [comment]
Thanks @Shoelace. 

This page says 

> Available Extensions for Oracle SQL Developer 3.2.x only. 
> ...
> Updated: July 2013

3.2 was the last version where ESDK 1.0 extensions were supported. Beginning with SQL Developer 4.0 third party extensions have to be based on ESDK 2.0. utPLSQL for SQL Developer is based on ESDK 2.0 and requires SQL Developer 4.1 (first version based on JDK 8). Hence, a request to be listed on this page would be wrong.

For me it looks like this page is not maintained anymore. I'm I right @thatjeffsmith?

**Comment by thatjeffsmith** [comment]
i think that's a pretty fair assessment
