### ISSUE TITLE
Add snippets for annotations and expectations

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#60]
It would be great to have separate Snippet section in SQLDeveloper to aid users.
The snippets could contain a full list of supported annotations and expectations for current version of utPLSQL.

Ideally, utPLSQL framework could include function to provide a list of supported annotations with description and syntax examples.

**Comment by PhilippSalvisberg** [comment]
Good idea. It would be nice if you could provide the snippets. You can create them within SQL Developer. They are stored in `UserSnippets.xml`. 

Based on that I should be able to provide them as part of the utPLSQL extension. I had a quick look at the `oracle.sqldeveloper.snippet` extension. There is no supported way to add additional snippets. There is a method called `SnippetAddin.registerSnippet`, but it is `protected`. However it should be possible to extend the existing `UserSnippets.xml` for predefined group names (e.g. `utPLSQL`). The event for the extension could be placed in the Preferences, similar how we currently extend the code templates. This way no user defined snippets are modified via explicit user interaction.

**Comment by PhilippSalvisberg** [comment]
>Ideally, utPLSQL framework could include function to provide a list of supported annotations with description and syntax examples.

If the utPLSQL framework provides this information, then the it should be possible to update the snippets based on that. However, choosing the right connection to get this information will be challenging, since the preference dialog does not have a connection context. Of course we could add a context menu on the connection to do the snippet update. The question is if we want to support older utPLSQL versions also. If the answer is yes, then we have to provide the snippets as part of the extension (at least for the older utPLSQL versions).

**Comment by lwasylow** [comment]
Hi is a first shot at snippets :)
[UserSnippets.zip](https://github.com/utPLSQL/utPLSQL-SQLDeveloper/files/3386881/UserSnippets.zip)

**Comment by PhilippSalvisberg** [comment]
Thanks @lwasylow . Good idea to provide a category for annotations and another one for expectations. I think it is even doable to maintain this `UserSnippets.xml` manually. 

I plan to include it in the [resource folder](https://github.com/utPLSQL/utPLSQL-SQLDeveloper/tree/master/sqldev/src/main/resources/org/utplsql/sqldev/resources) and provide a button in the preference dialog for the merge with the user's `UserSnippets.xml`. It's not perfect, but not that bad as well.

**Comment by lwasylow** [comment]
Yeah it's small enough to maintain manually and to be fair probably easier. Sounds like good plan
I actually like the snippets is like building a Lego now :)
