### ISSUE TITLE
Add ability to filter only failed / errored tests in list of executed tests

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#73]
The ability to sort results by status in the grid is great.
It wold be even better if the plugin would allow to narrow down the list of visible test to:
- only failed & errored
- only failed & errored & warnings
- only failed
- only errored
- only warnings

This could be implemented as toggles:
- show/hide success
- show/hide warnings
- show/hide errors
- show/hide failures

The functionality would be very useful when using "tree" view to display test results.

**Comment by PhilippSalvisberg** [comment]
Yes @jgebal, something like that would be useful. However, I would restrict the filter to some test status (success, failure, error, disabled). Warnings and info are independent of the test status. What do you expect to see when you hide success, hide errors, hide failures and show warnings? - Personally I think the following filters should be enough:
- show/hide success
- show/hide disabled
Disabled tests should not have warnings. But successful test may have warnings. If you do not show successful tests you won't see their warnings. That's ok. That's what I would expect.

**Comment by jgebal** [comment]
Sounds really good.
Show/hide toggle buttons for those two should be enough and defonitely very useful.
