### ISSUE TITLE
Flickering on fast running tests both Windows&Oracle Look&Feel

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#74]
When I run all utPLSQL tests (many of them are running really quickly) I often see that the UI is misbehaving.
- the tests count is flickering
- the progress bar is flickering
- the disabled count sometimes changes into in-progress icon
- the grid looks odd with title bar showing and hiding at the bottom of grid
- the current test name shows in unexpected location (grri header)

I'm not sure if i's related to:
- my graphics card (I'm on NVidia)
- my OS (Win 10 pro x64)
- my SQLDeveloper version (I'm on 18.2)
![image](https://user-images.githubusercontent.com/1398171/61189790-e1c49d00-a689-11e9-89cd-fea4d6601e90.png)
- the speed at which the tests are getting executed and the frame refresh rate in UI.

Maybe it would be possible to change the refresh rate to be say every 10-20ms to avoid excessive UI flickering while maintaining the "realtime" user-experience?

Attached gifs
 showing some of the flickering I've encountered.
![flickering-oracle1](https://user-images.githubusercontent.com/1398171/61189848-27359a00-a68b-11e9-88e2-c7337f70e1a3.gif)

![flickering-windows1](https://user-images.githubusercontent.com/1398171/61189850-33b9f280-a68b-11e9-9b3b-8b6f977a9a94.gif)

**Comment by PhilippSalvisberg** [comment]
Thanks @jgebal for reporting this. However, I experience flickering only in the table component. No issues with other components like progress bar or the counters. But I see that this happens for your GIFs while repainting the table component. Maybe this is related to your environment (OS, HW, JDK version, ...). I do not know.

Nonetheless, an update occurs on every realtime reporter event. It's not based on a timer. Flickering happens as soon as a scroll bar is required for the table component. You should never experience flickering when all tests are visible. On update the [`scrollRectToVisible`](https://docs.oracle.com/javase/8/docs/api/javax/swing/JComponent.html#scrollRectToVisible-java.awt.Rectangle-) method is called for the JTable component. This ensures that the currently executing test is visible. This call is causing the flickering. I have to find out how to avoid flickering while keeping the currently processed test visible.
