### ISSUE TITLE
Optimize availability check for "Run utPLSQL test" menu option

### ISSUE THREAD

**Issue by PhilippSalvisberg** [utPLSQL/utPLSQL-SQLDeveloper#76]
In the preferences you can configure if you want to check for the availability of the menu option "Run utPLSQL test". When set, the extension enables the menu option only when at least one test has been found. This may be slow for two reasons:

1. because the annotation cache needs to be updated
this happens only, if you do not use a DDL trigger to track changes, in this case changes are detected delayed, when running a test or when checking for availability of tests

2. large schemas
there is more data in the annotation cache and in the data dictionary, affecting the runtime performance of the queries, especially when no DDL trigger is in place, due to delayed annotation detection

Since version 3.1.8 the following functions are available in `ut_runner`: 

- `has_suites`
- `is_suite`
- `is_test`

These functions are optimized for performance and are faster than the generic table function `get_suites_info`. Hence these functions should be used whenever possible by the SQL Developer extension.

In fact these functions are available since utPLSQL version 3.1.3, but since version 3.1.8 they are considered reliable (see also utplsql/utplsql#976). Hence the use of this functions should be limited to utPLSQL version 3.1.8 and higher.

**Comment by jgebal** [comment]
@phsalvisberg 
I would need to double check but I think it was reliable before.
Only develop (3.1.8-develop) had a bug as I went too far with optimizetions.
Let me check change history to see.

**Comment by PhilippSalvisberg** [comment]
@jgebal I checked. My JUnit test case fails with 3.1.7. All functions return false instead of true, because they do not update the annotation cache (without using the DDL trigger). I have not tested that with 3.1.8 yet. Maybe this is an issue there as well.

**Comment by jgebal** [comment]
The functionality was introduced in [this change](https://github.com/utPLSQL/utPLSQL/commit/e1f1eec2024126a50168c2613bfeb9b2e989f7c1#diff-bdc0b3cc61b53c2284c6846baa374e36R756)

Since then it wasn't changed until [this change](https://github.com/utPLSQL/utPLSQL/commit/93890745347233fa1b4b49a1705de25ed18e349e#diff-bdc0b3cc61b53c2284c6846baa374e36R819) and then [this change](https://github.com/utPLSQL/utPLSQL/commit/6f0a939512ca44674f30e4d96a37afb348823948#diff-bdc0b3cc61b53c2284c6846baa374e36R616) in 3.1.8-develop

I'm no sure why the functions don't work for you in 3.1.7. They should as they should update cache.
Perhaps it's not worth digging in old versions. 

If this didn't work for you before 3.1.8, lets leave it active since 3.1.8 only.

**Comment by PhilippSalvisberg** [comment]
The problem is that `has_suite`, `is_suite` and `is_test` do not check if the annotation cache is up-to-date. This is a problem when you install utPLSQL with `install_headless.sql` instead of `install_headless_with_trigger.sql`. Hence this works in the develop environment and in our CI environment where `install_headless_with_trigger.sql` is used behind the scenes. These functions do not deliver a reliable result. Even in 3.1.8 :-(

**Comment by PhilippSalvisberg** [comment]
IMHO the functions should check if the DDL trigger is active. If not they have to update the annotation cache first. Similar logic as in `get_suites_info`.

**Comment by PhilippSalvisberg** [comment]
If this will not be fixed in 3.1.8 I'll have to undo this change.

**Comment by jgebal** [comment]
They do, and they always did.
line
```sql
    refresh_cache(l_owner_name);
```
Is responsible for doing the check and cache refresh.

**Comment by PhilippSalvisberg** [comment]
It's not working.

**Comment by jgebal** [comment]
I can have a look at this in the evening.

**Comment by PhilippSalvisberg** [comment]
@jgebal Why have you reopened this issue?

**Comment by jgebal** [comment]
Because we're discussing it and As you said, you might need to revert the change.
Feel free to close if you want. I can open a different issue on utPLSQL

**Comment by PhilippSalvisberg** [comment]
Ok, I checked it again. 
It works as expected (without trigger) in v3.1.8.
It does not work (without trigger) in v3.1.7. JUnit test fails.
Hence I close this issue.
