### ISSUE TITLE
Code templates

### ISSUE THREAD

**Issue by SteveOgh** [utPLSQL/utPLSQL-SQLDeveloper#91]
I was able to follow and complete all the documentation steps except:

_From scratch
Press the button <Create code templates> in the preferences_
where is this button? 

when I go into an editor and type ut_ ctrl-space I get none of the examples shown.  I'm not sure if there is an action I need to take (like when I went into preferences under utPLSQL and "pressed the button" and  imported the snippets) or it should be working out of the box.

**Comment by PhilippSalvisberg** [comment]
> Press the button `Create code templates` in the preferences

![image](https://user-images.githubusercontent.com/3883171/73012007-af081800-3e15-11ea-92ec-9346d677acf1.png)

this will create these templates

![image](https://user-images.githubusercontent.com/3883171/73012206-1faf3480-3e16-11ea-828b-765af30c2401.png)

and don't forget to press the `OK` button to save the preferences.

**Comment by PhilippSalvisberg** [comment]
I'm closing this issue. No heard back. I consider it answered.
