### ISSUE TITLE
Connections lost after installation

### ISSUE THREAD

**Issue by fguendling** [utPLSQL/utPLSQL-SQLDeveloper#98]
Hello,

after installation of the extension all but two of my Oracle connections are gone. I would like to understand why. I used SQLDeveloper 19.2 with Java 11 on macOS.

Did anyone face this issue before? Right now I don't know how I can get my connections back.

**Comment by PhilippSalvisberg** [comment]
Hi @fguendling, 

I'm sorry to hear that. However, I cannot tell you why this happened. I assume that it is not directly related to the installation of this extension. I know that the SQL Developer settings cache becomes corrupt, e.g. when having to kill a running SQL Developer or something goes wrong behind the scenes. In this case it might help to clear the `system_cache` folder. Search for  `ide.system.dir` in the `Properties` tab of the About Dialog. Quit SQL Developer. Change to this directory and delete the subfolder named `system_cache` and restart SQL Developer.

If this does not help, then have a look at the `${ide.system.dir}/o.jdeveloper.db.connection/connections.json`. It contains all connections stored by SQL Developer.

**Comment by PhilippSalvisberg** [comment]
Closing the issue. No reaction since more than two weeks.
